name: Package
on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up tags & labels
        id: set-tags
        run: |
          if [[ "{GITHUB_REF}" == *"-"* ]]; then
            echo "is pre-release"
            echo "DOCKER_TAG=prerelease-${GITHUB_REF##*/}" >> $GITHUB_ENV
          else
            echo "is stable release"
            echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

          echo "DOCKER_TAG=${DOCKER_TAG}"
          exit 1 # for now

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/caffeine-addictt/linguist:latest
            ghcr.io/caffeine-addictt/linguist:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/caffeine-addictt/linguist
